services:
  node1:
    build:
      context: .
    command: ["--port", "9000"]
    stdin_open: true
    tty: true
    networks:
      - chatnet

  node2:
    build:
      context: .
    command: ["--port", "9000", "--bootstrap", "${BOOTSTRAP}"]
    stdin_open: true
    tty: true
    networks:
      - chatnet

  node3:
    build:
      context: .
    command: ["--port", "9000", "--bootstrap", "${BOOTSTRAP}"]
    stdin_open: true
    tty: true
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge
